language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5

os:
  - linux

sudo: required

env:
  # Currently successful release
  - IMAGEMAGICK_VERSION=6.6.9-10
  # Ubuntu's current stable release
  - IMAGEMAGICK_VERSION=6.7.7-10
  # Latest 6.7 release
  - IMAGEMAGICK_VERSION=6.7.9-10
  # Latest 6.8 release
  - IMAGEMAGICK_VERSION=6.8.9-10
  # Try with HDRI support, we don't mind if this fails currently.
  - IMAGEMAGICK_VERSION=6.8.9-10 CONFIGURE_OPTIONS=--enable-hdri
  # Latest release
  - IMAGEMAGICK_VERSION=latest
  global:
    - CC_TEST_REPORTER_ID=d7788b6945c0e4f7ac0a138f44fa55f3572661be5c3e769357737eb3f4ef7041

matrix:
  exclude:
    - rvm: 2.0
      env: IMAGEMAGICK_VERSION=6.7.7-10
    - rvm: 2.0
      env: IMAGEMAGICK_VERSION=6.7.9-10
    - rvm: 2.0
      env: IMAGEMAGICK_VERSION=6.8.9-10
    - rvm: 2.0
      env: IMAGEMAGICK_VERSION=6.8.9-10 CONFIGURE_OPTIONS=--enable-hdri
  allow_failures:
    - env: IMAGEMAGICK_VERSION=6.7.7-10
    - env: IMAGEMAGICK_VERSION=6.7.9-10
      rvm: 2.1
    - env: IMAGEMAGICK_VERSION=6.7.9-10
      rvm: 2.2
    - env: IMAGEMAGICK_VERSION=6.8.9-10
      rvm: 2.1
    - env: IMAGEMAGICK_VERSION=6.8.9-10 CONFIGURE_OPTIONS=--enable-hdri
      rvm: 2.1
    - env: IMAGEMAGICK_VERSION=latest

before_install:
  - source before_install_$TRAVIS_OS_NAME.sh

install: bundle install --verbose

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a98c1112f5d60f97a532
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
